

all:
	echo "Go into child directories to run scripts"
	echo "Or type: make test_cases to remake the test case directory"

testcases:
	rm -Rf test_cases; \
	mkdir test_cases; \
	cd test_cases; \
	base=../../website; \
	cp $${base}/FamilyHistMenu.html . ;\
	cp $${base}/BixbyHannah1863.html .; \
	cp $${base}/CampbellCemListC_D.html .; \
	cp $${base}/HoytInez1871.html .; \
	cp $${base}/BurialsUpdatedRe1926MailList.html . ;\
	cp $${base}/CCCV1R1p33EmmaBuck.html . ;\
	cp $${base}/CampbellKate1853.html . ;\
	cp $${base}/VaughanEmma1854.html . ;\
	cp $${base}/CCCV1R2p32AnnVanDusen.html . ;\
	cp $${base}/CampbellMaria1842.html . ;
