#!/usr/bin/expect
spawn sftp -oHostKeyAlgorithms=+ssh-dss ftp.campbellluggblackwell.com
expect "Name (ftp.campbellluggblackwell.com:runner):"
send "${BLUEHOST_USERNAME}@campbellluggblackwell.com\r"
expect "Password:"
send "${BLUEHOST_PASSWORD}\r"
expect "ftp>"
send "cd public_html\r"
expect "ftp>"
send "mget *.svg .\r"
expect "ftp>"
send "bye\r"
