#!/usr/bin/expect
spawn sftp -oHostKeyAlgorithms=+ssh-dss [lindex $argv 0]@ftp.campbellluggblackwell.com
expect "Are you sure"
send "yes\r"
#expect "Name (ftp.campbellluggblackwell.com:runner):"
#send "[lindex $argv 0]@campbellluggblackwell.com\r"
expect "ssword:"
send "[lindex $argv 1]\r"
expect "ftp>"
send "cd public_html\r"
expect "ftp>"
send "mget -l 1 * .\r"
expect "ftp>"
sleep 2
send "bye\r"
