#!/usr/bin/expect
spawn sftp -oHostKeyAlgorithms=+ssh-dss ftp.campbellluggblackwell.com
expect "Are you sure"
send "yes\r"
expect "Name (ftp.campbellluggblackwell.com:runner):"
send "$1@campbellluggblackwell.com\r"
expect "Password:"
send "$2\r"
expect "ftp>"
send "cd public_html\r"
expect "ftp>"
send "mget *.svg .\r"
expect "ftp>"
send "bye\r"
